FROM ubuntu:22.04 as base
ENV DEBIAN_FRONTEND=noninteractive
ENV PROJECT=udp-proxy-2020

RUN apt-get update && \
    apt-get install -y libpcap0.8 libpcap0.8-dev make git gcc golang-1.18-go && \
    apt-get clean
RUN mkdir -p /build

FROM base
WORKDIR /build
COPY . /build/$PROJECT/

WORKDIR /build/$PROJECT 
ENV GOROOT=/usr/lib/go-1.18
ENV PATH=/build/bin:${GOROOT}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ENTRYPOINT make .linux-amd64
